esphome:
  name: espatrea
  includes: espatrea.h

esp8266:
  board: d1_mini

# Enable logging
logger:
  hardware_uart: UART1

# Enable Home Assistant API
api:
  encryption:
    key: "vGmcGeQv1t0YS8dYxiWZ+18dVwOTM8Wd5xJNhZfAHL0="

ota:
  - platform: esphome
    password: "ee63ad1b7179078c6f6551b408078ec2"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESPAtrea Fallback Hotspot"
    password: "DB03b2AyhjsK"
  manual_ip:
    static_ip: 192.168.3.204
    gateway: 192.168.3.1
    subnet: 255.255.255.0
  power_save_mode: none

captive_portal:

uart:
  id: uart_bus
  rx_pin: GPIO3
  tx_pin: GPIO1
  rx_buffer_size: 20
  baud_rate: 300
  
text_sensor:
  - platform: custom
    lambda: |-
      auto uart = new AtreaUart(id(uart_bus));
      auto atrea = new AtreaTextSensor();
      App.register_component(uart);
      App.register_component(atrea);
      return {atrea->cp07_rezim, atrea->cp07_intenzita, atrea->cp07_rizeni_teploty, atrea->atrea_rezim, atrea->atrea_intenzita, atrea->atrea_chyby};
    text_sensors:
      - name: "CP07 režim VZT"
      - name: "CP07 intenzita"
      - name: "CP07 nastavení teplot"
      - name: "Atrea režim VZT"
      - name: "Atrea intenzita"
      - name: "Atrea chyby"

sensor:
  - platform: custom
    lambda: |-
      auto atrea = new AtreaSensor();
      App.register_component(atrea);
      return {atrea->atrea_teplota_TE, atrea->atrea_teplota_TA, atrea->atrea_teplota_TI2, atrea->atrea_cirkulace};
    sensors:
      - name: "Atrea venkovní teplota"
        unit_of_measurement: "°C"
      - name: "Atrea teplota výměníku"
        unit_of_measurement: "°C"
      - name: "Atrea teplota za rekuperátorem"
        unit_of_measurement: "°C"
      - name: "Atrea přisávání cirkulace"
        unit_of_measurement: "%"

  - platform: homeassistant
    id: esp_teplota_termostatu
    entity_id: sensor.teplota_termostatu
    internal: true

binary_sensor:
  - platform: custom
    lambda: |-
      auto atrea = new AtreaBinarySensor();
      App.register_component(atrea);
      return {atrea->cp07_bypass, atrea->atrea_topi, atrea->atrea_chladi, atrea->atrea_narazove_vetrani, atrea->atrea_fx, atrea->atrea_D1, atrea->atrea_D2, atrea->atrea_D3, atrea->atrea_D4, atrea->atrea_klapka_SR, atrea->atrea_bypass_SB, atrea->atrea_YV, atrea->atrea_K, atrea->atrea_OC1, atrea->esp_aktivni_ovladac, atrea->esp_topna_sezona, atrea->esp_bypass, atrea->esp_topeni, atrea->esp_chlazeni};
    binary_sensors:
      - name: "CP07 bypass"
      - name: "Atrea topení"
      - name: "Atrea chlazení"
      - name: "Atrea nárazové větrání"
      - name: "Atrea fx"
      - name: "Atrea IO vstup D1"
      - name: "Atrea IO vstup D2"
      - name: "Atrea IO vstup D3"
      - name: "Atrea IO vstup D4"
      - name: "Atrea IO klapka sání SR"
      - name: "Atrea IO bypass SB"
      - name: "Atrea IO TČ topení YV"
      - name: "Atrea IO kotel K"
      - name: "Atrea IO TČ chlazení OC1"
      - name: "ESP aktivní ovladač"
      - name: "ESP topná sezóna"
      - name: "ESP bypass"
      - name: "ESP topeni"
      - name: "ESP chlazeni"

switch:
  - platform: template
    id: topeni_ctrl
    optimistic: true
    turn_on_action:
      - switch.turn_off: chlazeni_ctrl
    internal: true
        
  - platform: template
    id: chlazeni_ctrl
    optimistic: true
    turn_on_action:
      - switch.turn_off: topeni_ctrl
    internal: true      

select:
  - platform: template
    name: "ESP režim VZT"
    id: esp_rezim_vzt
    optimistic: true
    restore_value: true
    options:
      - "Rovnotlaké větrání"
      - "Cirkulační větrání"
      - "Cirkulace"
      - "Cirkulace závislá"
      - "Přetlakové větrání"
    initial_option: "Cirkulace závislá"
    
  - platform: template
    name: "ESP intenzita"
    id: esp_intenzita
    optimistic: true
    restore_value: true
    options:
      - Vypnuto
      - Střední
      - Maximální
    initial_option: "Střední"

climate:
  - platform: thermostat
    name: "Termostat domu"
    id: termostat_domu
    sensor: esp_teplota_termostatu
    min_cooling_off_time: 300s
    min_cooling_run_time: 300s
    min_heating_off_time: 300s
    min_heating_run_time: 300s
    min_idle_time: 30s
    visual:
      min_temperature: 16
      max_temperature: 28
      temperature_step:
        target_temperature: 0.5
        current_temperature: 0.1    
    cool_action:
      - switch.turn_on: chlazeni_ctrl
    heat_action:
      - switch.turn_on: topeni_ctrl
    idle_action:
      - switch.turn_off: chlazeni_ctrl
      - switch.turn_off: topeni_ctrl
    default_preset: Doma
    preset:
      - name: Doma
        default_target_temperature_low: 21.5 °C
        default_target_temperature_high: 24 °C
      - name: Pryč
        default_target_temperature_low: 18 °C
        default_target_temperature_high: 25 °C        
