esphome:
  name: espatrea
  platformio_options:
    build_flags:
      - -std=gnu++17

esp8266:
  board: d1_mini

# Enable logging
logger:
  hardware_uart: UART1
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "xxx"

ota:
  - platform: esphome
    password: "yyy"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "ESPAtrea Fallback Hotspot"
    password: "zzz"
  manual_ip:
    static_ip: 192.168.1.204
    gateway: 192.168.1.1
    subnet: 255.255.255.0
  power_save_mode: none

captive_portal:

# External component configuration
external_components:
  - source:
      type: local
      path: components
    components: [ atrea ]

uart:
  id: uart_bus
  rx_pin: GPIO3
  tx_pin: GPIO1
  rx_buffer_size: 20
  baud_rate: 300

# Atrea component
atrea:
  id: atrea_component
  uart_id: uart_bus
  thermostat_id: termostat_domu
  esp_intensity_id: esp_intenzita
  esp_mode_id: esp_rezim_vzt
  esp_heating_id: esp_topeni
  esp_cooling_id: esp_chlazeni

# Text sensors
text_sensor:
  - platform: atrea
    atrea_id: atrea_component
    cp07_mode:
      name: "CP07 režim VZT"
      icon: "mdi:air-conditioner"
    cp07_intensity:
      name: "CP07 intenzita"
      icon: "mdi:wind-power"
    cp07_temperature_control:
      name: "CP07 nastavení teplot"
      icon: "mdi:thermometer"
    cp07_bypass:
      name: "CP07 bypass"
    atrea_mode:
      name: "Atrea režim VZT"
      icon: "mdi:air-conditioner"
    atrea_intensity:
      name: "Atrea intenzita"
      icon: "mdi:wind-power"
    atrea_errors:
      name: "Atrea chyby"
      icon: "mdi:fan-alert"

# Sensors
sensor:
  - platform: atrea
    atrea_id: atrea_component
    outdoor_temperature:
      name: "Atrea venkovní teplota"
      icon: "mdi:sun-thermometer-outline"
    exchanger_temperature:
      name: "Atrea teplota výměníku"
      icon: "mdi:thermometer-lines"
    recuperator_temperature:
      name: "Atrea teplota za rekuperátorem"
      icon: "mdi:thermometer"
    circulation:
      name: "Atrea přisávání cirkulace"
      icon: "mdi:speedometer"

  - platform: homeassistant
    id: esp_teplota_termostatu
    entity_id: sensor.teplota_termostatu
    unit_of_measurement: "°C"
    internal: true

# Binary sensors
binary_sensor:
  - platform: atrea
    atrea_id: atrea_component
    atrea_heating:
      name: "Atrea topení"
      icon: "mdi:radiator"
    atrea_cooling:
      name: "Atrea chlazení"
      icon: "mdi:snowflake"
    atrea_boost_ventilation:
      name: "Atrea nárazové větrání"
      icon: "mdi:weather-windy"
    atrea_d1:
      name: "Atrea IO vstup D1"
    atrea_d2:
      name: "Atrea IO vstup D2"
    atrea_d3:
      name: "Atrea IO vstup D3"
    atrea_d4:
      name: "Atrea IO vstup D4"
    atrea_damper_sr:
      name: "Atrea IO klapka sání SR"
    atrea_bypass_sb:
      name: "Atrea IO bypass SB"
    atrea_yv:
      name: "Atrea IO TČ topení YV"
    atrea_k:
      name: "Atrea IO kotel K"
    atrea_oc1:
      name: "Atrea IO TČ chlazení OC1"
    esp_active_controller:
      name: "ESP aktivní ovladač"
    esp_heating_season:
      name: "ESP topná sezóna"
    esp_bypass:
      name: "ESP bypass"

# Selects
select:
  - platform: template
    name: "ESP režim VZT"
    id: esp_rezim_vzt
    optimistic: true
    restore_value: true
    options:
      - "Rovnotlaké větrání"
      - "Cirkulační větrání"
      - "Cirkulace závislá"
      - "Cirkulace"
      - "Přetlakové větrání"
    initial_option: "Cirkulace závislá"
    
  - platform: template
    name: "ESP intenzita"
    id: esp_intenzita
    optimistic: true
    restore_value: true
    options:
      - Vypnuto
      - Střední
      - Maximální
    initial_option: "Střední"

# Switches
switch:
  - platform: template
    name: "ESP topení"
    id: esp_topeni
    optimistic: true
    turn_on_action:
      - switch.turn_off: esp_chlazeni
        
  - platform: template
    name: "ESP chlazení"
    id: esp_chlazeni
    optimistic: true
    turn_on_action:
      - switch.turn_off: esp_topeni

# Climate control
climate:
  - platform: thermostat
    name: "Termostat domu"
    id: termostat_domu
    sensor: esp_teplota_termostatu
    min_cooling_off_time: 30s
    min_cooling_run_time: 30s
    min_heating_off_time: 30s
    min_heating_run_time: 30s
    min_idle_time: 30s
    visual:
      min_temperature: 16
      max_temperature: 28
      temperature_step:
        target_temperature: 0.5
        current_temperature: 0.1
    heat_deadband: 0.25
    heat_overrun: 0.25
    cool_deadband: 0.2
    cool_overrun: 0.2
    cool_action:
      - switch.turn_on: esp_chlazeni
    heat_action:
      - switch.turn_on: esp_topeni
    idle_action:
      - switch.turn_off: esp_chlazeni
      - switch.turn_off: esp_topeni
    heat_mode: 
      then:
        - switch.turn_off: esp_chlazeni
    cool_mode: 
      then:
        - switch.turn_off: esp_topeni
    off_mode: 
      then:
        - switch.turn_off: esp_chlazeni
        - switch.turn_off: esp_topeni
    default_preset: Doma
    preset:
      - name: Doma
        default_target_temperature_low: 21.5 °C
        default_target_temperature_high: 24 °C
      - name: Pryč
        default_target_temperature_low: 18 °C
        default_target_temperature_high: 25 °C
